export const CODE_RESPONSE = Object.freeze({
    // API Authentication
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_EMAIL_ALREADY_EXIST: "AUTH_REGISTER_EMAIL_ALREADY_EXIST",
    AUTH_REGISTER_ERROR: "AUTH_REGISTER_ERROR",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_INCORRECT_PASSWORD: "AUTH_LOGIN_INCORRECT_PASSWORD",
    AUTH_LOGIN_EMAIL_NOT_FOUND: "AUTH_LOGIN_EMAIL_NOT_FOUND",
});
